language: python
sudo: false

matrix:
  include:
    - python: 3.4

install:
  - pip install -e git+https://github.com/ipython/ipython.git#egg=IPython
  - pip install -e git+https://github.com/getnikola/nikola.git#egg=nikola
  - pip install mistune jsonschema jsonpointer
  - pip install jinja2


script:
  - git config --global user.email "TravisBot@nomail"
  - git config --global user.name "TravisBot"
  - git config --global push.default simple
  - cd ..
  - git clone https://github.com/Carreau/nikola-blog blog
  - git clone https://github.com/Carreau/carreau.github.io blog/output
  - ln -s ../posts blog/posts
  - cd blog
  - pwd
  - ls -la posts
  - nikola build

after_success:
  |
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'master' ]]; then
    
    echo "Will push to ghpages"
    pwd
    cd ../posts
    echo '================'
    ls -la
    openssl aes-256-cbc -K $encrypted_b04f054e19e0_key -iv $encrypted_b04f054e19e0_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
    eval `ssh-agent -s`
    chmod 600 .travis/travis_rsa
    ssh-add .travis/travis_rsa
    cd ../blog/output
    git remote add ghpages ssh://github.com/Carreau/carreau.github.io
    echo '================'
    pwd
    echo '================'
    git remote -v
    echo '================'
    git status
    echo '================'
    git add .
    echo '================'
    git commit -am'autocommit autobuild'
    echo '================'
    git diff --stat
    echo '================'
    git status
    echo '================'
    ls -la posts
    echo '================'
    ls output/2015/
    echo "should I push?"
    #git push ghpages master:master
  else
    echo "Will only deploy docs build from blog from master branch"
  fi
