language: python
sudo: false

matrix:
  include:
    - python: 3.4

install:
  - pip install nikola
  - pip install mistune jsonschema jsonpointer
  - pip install jinja
  - pip install git://github.com/ipython/ipython.git


script:
  - git config --global user.email "TravisBot@nomail"
  - git config --global user.name "TravisBot"
  - git config --global push.default simple
  - git clone ssh://github/Carreau/nikola-blog blog
  - git clone ssh://github/carreau/carreau.github.io blog/output
  - ln -s . blog/posts
  - cd blog
  - nikola build

after_success:
  |
  if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == 'master' ]]; then
    echo "Will push to ghpages"
    # shoudl decrypt ssh key
    #openssl aes-256-cbc -K $encrypted_7d2843e800b0_key -iv $encrypted_7d2843e800b0_iv -in .travis/travis_id_rsa_2048.enc -out .travis/travis_id_rsa_2048 -d
    #eval `ssh-agent -s`
    #chmod 600 .travis/travis_id_rsa_2048
    #ssh-add .travis/travis_id_rsa_2048
    #cd gh-pages
    #git push ghpages
  else
    echo "Will only deploy docs build from blog from master branch"
  fi
